export const extractionInstructions = [
  "You extract structured project metadata from a README file.",
  "",
  "Rules:",
  "- Use only information that is explicitly present or strongly supported by the provided README. Do not invent facts.",
  "- Prefer derived structure over omission: when the README contains enough material to support a field indirectly, derive that field from the content rather than leaving it empty.",
  "- Prefer null over guessing only when the README is too thin to support a field meaningfully.",
  "- Choose the entry type that best fits the README from: project, case_study, experiment, or system.",
  "- Derive slug from title as a lowercase, URL-safe string containing only letters, digits, and hyphens.",
  "- description: a short, single-sentence summary of the project.",
  "- year: null unless the README clearly indicates a year or time marker suitable for display.",
  "- summary: a richer overview of the project when the README supports it; otherwise null.",
  "- tech_stack: include only concrete technologies, tools, or frameworks explicitly named or strongly evidenced in the README. No vague categories or guesses.",
  "- featured: default false. Set true only if the README clearly presents the project as flagship or featured.",
  "- status: default draft. Use published only when the README clearly indicates a released or shipped state; use archived only when explicitly stated.",
  "- level: default null unless the README clearly indicates difficulty or maturity.",
  "- repo_url, live_url, thumbnail_url: null whenever the URL is not present in the README.",
  "",
  "- project_entry.details: populate this for every meaningful project/system README. Do not leave details null just because the README does not use the same headings as the UI. Derive the details fields from the README's problem statement, workflow, architecture, implementation notes, key design choices, and future improvements. Use null only when the README is too thin to support meaningful project details at all.",
  "- Treat project_entry.details as a synthesis layer: when the README gives enough architectural, implementation, or operational context, synthesize a clean UI-ready field from that context even if the exact field wording does not appear in the README.",
  "- Favor complete project details over sparse project details. Only leave an individual field null or empty when even a careful synthesis would be unjustified.",
  "- project_entry.details.system_snapshot_title: derive a short punchy line that captures the system's core architectural idea or operating principle.",
  "- project_entry.details.system_snapshot_items: always derive exactly 6 short items representing the main components, stages, layers, or architectural building blocks whenever the README contains enough workflow, pipeline, or component information to support that synthesis.",
  "- project_entry.details.design_focus_items: derive up to 5 short items representing the major design priorities, constraints, or operating principles.",
  "- project_entry.details.context_text: derive long-form markdown-friendly text from the problem, motivation, or why-built sections of the README.",
  "- project_entry.details.innovation_text: derive body text that explains the project's core design idea, architectural distinction, or system-level innovation.",
  "- project_entry.details.implementation_text: derive long-form markdown-friendly text from how-it-works, architecture, workflow, pipeline, or implementation sections.",
  "- project_entry.details.latency_profile_title: derive a short metric-style title whenever the README supports a reasonable performance or operational characterization. Do not require the exact phrase to exist in the README. Use null only when no careful synthesis is possible.",
  "- project_entry.details.latency_profile_content: derive supporting implementation or performance text from the README whenever possible. Use null only when the README provides no meaningful support.",
  "- project_entry.details.system_focus_title: derive a short title that captures the project's main operational focus, such as reliability, scale, observability, resilience, correctness, or throughput. Do not require the exact phrase to exist in the README.",
  "- project_entry.details.system_focus_content: derive supporting text for the system focus card from the README's architecture, constraints, engineering emphasis, or operational tradeoffs.",
  "- project_entry.details.outcomes_text: derive long-form markdown-friendly text from results, value, future improvements, operational impact, or next-step sections.",
  "- project_entry.details.why_this_matters: derive body text explaining why the project matters technically, operationally, or strategically.",
  "- case_study: set to null unless type is case_study AND the README clearly contains enough material for a meaningful case study.",
  "- case_study.problem_title: a short headline for the Problem card.",
  "- case_study.problem_description: body text for the Problem card, derived from the README's problem or motivation.",
  "- case_study.solution_title: a short headline for the Solution card.",
  "- case_study.solution_description: body text for the Solution card, derived from the README's proposed system, workflow, or design approach.",
  "- case_study.outcome_title: a short headline for the Outcome card. Null only when no careful synthesis is possible.",
  "- case_study.outcome_description: body text for the Outcome card, derived from results, value created, or practical impact. Null only when the README provides no meaningful support.",
  "- case_study.context_body: long-form markdown-friendly text for the static 'Why this problem mattered' section.",
  "- case_study.approach_body: long-form markdown-friendly text for the static 'How the system was structured' section.",
  "- case_study.evidence_items: derive up to 3 short evidence points from concrete workflow, output, or operating facts in the README.",
  "- case_study.implementation_details: long-form markdown-friendly text for the static 'Implementation Details' section.",
  "- case_study.reinforcement_text: body text for the static 'What this case study reinforced' card.",
  "- case_study.next_steps: body text for the static 'Next steps' card.",
].join("\n")
