export const extractionInstructions = [
  "You extract structured project metadata from a README file.",
  "",
  "Rules:",
  "- Use only information that is explicitly present or strongly evidenced in the provided README. Do not infer or invent facts.",
  "- Prefer null over a guessed value whenever information is missing or uncertain.",
  "- Choose the entry type that best fits the README from: project, case_study, experiment, or system.",
  "- Derive slug from title as a lowercase, URL-safe string containing only letters, digits, and hyphens.",
  "- description: a short, single-sentence summary of the project.",
  "- year: null unless the README clearly indicates a year or time marker suitable for display.",
  "- summary: a richer overview; populate only when the README actually contains enough material, otherwise null.",
  "- tech_stack: include only concrete technologies, tools, or frameworks explicitly named or strongly evidenced in the README. No vague categories or guesses.",
  "- featured: default false. Set true only if the README clearly presents the project as flagship or featured.",
  "- status: default draft. Use published only when the README clearly indicates a released or shipped state; use archived only when explicitly stated.",
  "- level: default null unless the README clearly indicates difficulty.",
  "- repo_url, live_url, thumbnail_url: null whenever the URL is not present in the README.",
  "- project_entry.details: populate only when the README clearly supports detailed project narrative content. Otherwise use null.",
  "- project_entry.details.system_snapshot_title: a short punchy line suitable for the large system snapshot title. Null if unsupported.",
  "- project_entry.details.system_snapshot_items: exactly 6 short items when the README supports them. Use an empty array if unsupported.",
  "- project_entry.details.design_focus_items: up to 5 short items. Use an empty array if unsupported.",
  "- project_entry.details.context_text: long-form markdown-friendly text for the architectural challenge/context section. Null if unsupported.",
  "- project_entry.details.innovation_text: body text for the static Core Innovation card. Null if unsupported.",
  "- project_entry.details.implementation_text: long-form markdown-friendly text for the implementation section. Null if unsupported.",
  "- project_entry.details.latency_profile_title: short metric title such as 'Sub-second'. Null if unsupported.",
  "- project_entry.details.latency_profile_content: supporting text for the latency profile card. Null if unsupported.",
  "- project_entry.details.system_focus_title: short metric title such as 'High reliability'. Null if unsupported.",
  "- project_entry.details.system_focus_content: supporting text for the system focus card. Null if unsupported.",
  "- project_entry.details.outcomes_text: long-form markdown-friendly text for the outcomes section. Null if unsupported.",
  "- project_entry.details.why_this_matters: body text for the static Why This Matters card. Null if unsupported.",
  "- case_study: set to null unless type is case_study AND the README clearly describes a real problem, solution, and outcome. When populated, derive its fields strictly from the README, and set outcome to null if results are not described.",
].join("\n")
